# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target '30 Seconds' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 30 Seconds
  pod 'SnapKit', '~> 5.0.0'

  target '30 SecondsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
